### PR TITLE
Fix components cleanup

### LINKED ISSUE #703: Adding/removing providers in management object results in deletion of managed clusters.
# Issue

When changing providers (adding or removing) the helm releases connected to managed clusters are being deleted by `management` controller and then immediately recreated by `managedcluster` controller.

Logs:

```
2024-12-02T20:05:55Z	INFO	Reconciling Management	{"controller": "management", "controllerGroup": "hmc.mirantis.com", "controllerKind": "Management", "Management": {"name":"hmc"}, "namespace": "", "name": "hmc", "reconcileID": "5d0f6d25-dc34-4144-80c5-2d6798e928e9"}
2024-12-02T20:05:55Z	INFO	Found component to remove	{"controller": "management", "controllerGroup": "hmc.mirantis.com", "controllerKind": "Management", "Management": {"name":"hmc"}, "namespace": "", "name": "hmc", "reconcileID": "5d0f6d25-dc34-4144-80c5-2d6798e928e9", "component_name": "vsphere-dev"}
2024-12-02T20:05:55Z	INFO	Removed HelmRelease	{"controller": "management", "controllerGroup": "hmc.mirantis.com", "controllerKind": "Management", "Management": {"name":"hmc"}, "namespace": "", "name": "hmc", "reconcileID": "5d0f6d25-dc34-4144-80c5-2d6798e928e9", "reference": "hmc-system/vsphere-dev"}
2024-12-02T20:05:55Z	INFO	Reconciling ManagedCluster	{"controller": "managedcluster", "controllerGroup": "hmc.mirantis.com", "controllerKind": "ManagedCluster", "ManagedCluster": {"name":"vsphere-dev","namespace":"hmc-system"}, "namespace": "hmc-system", "name": "vsphere-dev", "reconcileID": "1046080e-c2a0-437d-ad5a-554072de12c1"}
2024-12-02T20:05:55Z	INFO	Downloading Helm chart	{"controller": "managedcluster", "controllerGroup": "hmc.mirantis.com", "controllerKind": "ManagedCluster", "ManagedCluster": {"name":"vsphere-dev","namespace":"hmc-system"}, "namespace": "hmc-system", "name": "vsphere-dev", "reconcileID": "1046080e-c2a0-437d-ad5a-554072de12c1"}
2024/12/02 20:05:55 [DEBUG] GET http://source-controller.hmc-system.svc.cluster.local./helmchart/hmc-system/vsphere-standalone-cp-0-0-3/vsphere-standalone-cp-0.0.3.tgz
2024-12-02T20:05:55Z	INFO	Initializing Helm client	{"controller": "managedcluster", "controllerGroup": "hmc.mirantis.com", "controllerKind": "ManagedCluster", "ManagedCluster": {"name":"vsphere-dev","namespace":"hmc-system"}, "namespace": "hmc-system", "name": "vsphere-dev", "reconcileID": "1046080e-c2a0-437d-ad5a-554072de12c1"}
2024-12-02T20:05:55Z	INFO	Validating Helm chart with provided values	{"controller": "managedcluster", "controllerGroup": "hmc.mirantis.com", "controllerKind": "ManagedCluster", "ManagedCluster": {"name":"vsphere-dev","namespace":"hmc-system"}, "namespace": "hmc-system", "name": "vsphere-dev", "reconcileID": "1046080e-c2a0-437d-ad5a-554072de12c1"}
```

## Repro steps

1. Create managed cluster (I created vsphere cluster), ensure that helm release is installed properly and `Cluster` object is created properly
2. Edit management cluster and add or remove unused provider (I removed and added `cluster-api-provider-aws`)
3. Check `helmrelease` related to managed cluster. Note that creation time was changed and release was recreated.

**Additional note**: When installed in airgap environment a number of public cloud controllers were not initialized properly (on purpose) by no passing airgap flag. This caused deletion and recreation happening every 10 seconds for all ManagedClusters. Unfortunately I couldn't reproduce it properly.

# Conclusions

Most probably caused by #584 . It looks like selector is too broad and we should avoid deleting helm releases related to managed cluster.
Also most probably this will not affect managed clusters created in namespaces other than `hmc-system` (not tested).

### PR DESCRIPTION
**Pull request by zerospiel**
* add helm-release label to the helmreleases installed by the HMC management part
* cleanup helmreleases only if removed and the new label value equals to the mgmt part
* small refactor to fix linter

Closes #703

### CODE REVIEW

File: api/v1alpha1/managedcluster_types.go [hunk 1]
```diff
@@ -28,6 +28,7 @@ const (
 	FluxHelmChartNameKey      = "helm.toolkit.fluxcd.io/name"
 	FluxHelmChartNamespaceKey = "helm.toolkit.fluxcd.io/namespace"
 
+	PartOfLabel          = "hmc.mirantis.com/part-of" // PartOfNameLabel label key with value containing the name of the release owner
```
Comment (Kshatrix) [inline api/v1alpha1/managedcluster_types.go:31]: I think we can figure this out based on ownership. ManagedCluster-owned helmreleases have an OwnerReference set already. We can assume for now, that helmreleases without ownerreferences belong to providers (and maybe set ORs for them later)

**Review by Kshatrix — CHANGES_REQUESTED** [review]

File: api/v1alpha1/managedcluster_types.go (hunk 1 above)
Comment (zerospiel) [reply api/v1alpha1/managedcluster_types.go]: Thanks, fixed it with a simple length check and left a simple check just in case (noop because of the length check)

**Review by Kshatrix — APPROVED** [review]
